# Generated by Django 3.1.3 on 2021-03-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllink',
            name='original_url',
            field=models.URLField(unique=True),
        ),
    ]
